### ISSUE TITLE
Use the history API

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/noddity#31]
What do you think about using the history API after static rendering (#30) is completed?

The history API is [80% supported](http://caniuse.com/#feat=history), and anyone without it could fall back to http requests.

See [ponyfoo/stop-breaking-the-web](https://ponyfoo.com/articles/stop-breaking-the-web#emphasize-content-first).

The obvious downside being, that hashbang urls that are in use right now would have to be supported, or redirected to the correct page.

**Comment by TehShrike** [comment]
I would have used the history API from the beginning, except that it doesn't fire an [onhashchange](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange) equivalent when you click on a link.

[popstate](https://developer.mozilla.org/en-US/docs/Web/Events/popstate) doesn't fire when you click on a link, so we would also have to implement some kind of hack to make all links not actually visit the link that they pointed to, and fiddle with the history manually in those cases.

Related: https://github.com/TehShrike/abstract-state-router/issues/48

**Comment by sundarj** [comment]
`popstate` doesn't fire when you click on a link because that's not how the History API works. If you want the link to modify the history programmatically you have to `preventDefault` and then fire an equivalent `pushState`.

**Comment by TehShrike** [comment]
What event is fired when you click on a link where you can call `event.preventDefault()` and cancel the regular navigation to that other page?

**Comment by sundarj** [comment]
Well, `click` is: https://jsfiddle.net/df78oofa/

**Comment by TehShrike** [comment]
Yeah, watching for all click events and doing magical things when the clicked thing happens to be a link is the only way I know of too.

**Comment by sundarj** [comment]
I wouldn't call it 'magic', it's simply a different kind of navigation

**Comment by TehShrike** [comment]
Well, handling all click events and adding non-standard behavior to core browser behavior (what happens when you click on `a` elements) is a bit more magical than I usually roll.  Not that it's inappropriate.

**Comment by TehShrike** [comment]
I'm going to close this for now, but the idea will be implemented eventually when we start working on the static-server support for Noddity.

**Comment by sundarj** [comment]
https://github.com/erikringsmuth/pushstate-anchor just found this
