### ISSUE TITLE
Root post will sometimes not refresh

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/noddity#32]
We're tracking this on workflowy, but I would like it here for discussion, pictures, etc.

**Comment by ArtskydJ** [comment]
![capture](https://cloud.githubusercontent.com/assets/1833684/13940522/458e4428-efac-11e5-8753-ad0ac9f1523c.PNG)

Here is a screenshot of the entire indexeddb contents of a replication.

**Comment by ArtskydJ** [comment]
![capture](https://cloud.githubusercontent.com/assets/1833684/13940545/87e5d318-efac-11e5-8758-4d5cbd2a25b3.PNG)

Here is a screenshot of the console...

**Comment by ArtskydJ** [comment]
![capture](https://cloud.githubusercontent.com/assets/1833684/13940581/d6fea6d2-efac-11e5-8213-d8d62a92a63c.PNG)

Here is a screenshot of the first 100 seconds or so (it repeats after this...)

**Comment by TehShrike** [comment]
I know you did some work on this in other repos, is this still open?  Are there any action items left?

**Comment by ArtskydJ** [comment]
I forget the details, but we were unable to figure out why a key was deleted. We thought it might have been a race condition.

We decided to try the `setInterval` thing on `expire-unused-keys` or `levelup-cache`, in case this was a race condition.

Perhaps it could be closed for now. I don't think I have a test case to replicate it. If it pops up again, we can re-open, or create a new issue.

**Comment by TehShrike** [comment]
This should be fixed by https://github.com/TehShrike/levelup-cache/issues/3, https://github.com/TehShrike/expire-unused-keys/issues/6, and https://github.com/TehShrike/expire-unused-keys/issues/7.
